### ISSUE TITLE
unbekannte Plugin-Aktion: category

### ISSUE THREAD

**Issue by pselsa** [tleilax/SchwarzesBrettPlugin#1]
Beim Aufrufen des Plugin in einem Stud.IP 5.3 tritt folgender Fehler auf:

```
Typ: Exception
Nachricht: unbekannte Plugin-Aktion: category
Code: 0
Stack trace:
#$ lib/plugins/core/StudIPPlugin.class.php(171)
#0 public/plugins_packages/UOL/SchwarzesBrettPlugin/SchwarzesBrettPlugin.class.php(148): StudIPPlugin->perform('category')
#1 public/plugins.php(61): SchwarzesBrettPlugin->perform('category')
#2 {main}
```

**Comment by tleilax** [comment]
Siehe https://gitlab.studip.de/uol/plugins/SchwarzesBrettPlugin/-/issues/136
